# minimalist service to handle the loading of supported languages stored 
# in locales/supported.json (generated by a grunt task here)
class LanguagesService
    @$inject: ['Restangular', '$translate', '$http', '$rootScope']
    
    constructor: (Restangular, @translate, @http, @rootScope)->
        @list = Restangular.all('languages').getList()
        @rootScope.$watch => 
                @translate.uses()
            , @setCurrent, true
            
        @rootScope.$watch => 
                @current
            , @setCurrent, true
        
    setCurrent: (lang=null)=>
        if lang is null
            lang = @translate.uses()
        @current = lang
        @translate.uses(@current)
        @updateDjangoLang(@current)

    updateDjangoLang: (lang)=>
        conf =
            method: 'POST'
            url: '/i18n/setlang/'
            data:
                language: lang

        @http(conf)

angular.module('storiesServices').service "languagesService", LanguagesService