# minimalist service to handle the loading of supported languages stored 
# in locales/supported.json (generated by a grunt task here)
class LanguagesService
    @$inject: ['Restangular', '$translate', '$rootScope']
    
    constructor: (Restangular, @translate, @rootScope)->
        @list = Restangular.all('languages').getList()
            
        @rootScope.$watch => 
                @current
            , @setCurrent, true
        
        @rootScope.$watch =>
                @translate.uses()
            , =>
                @current = @translate.uses() unless @current is @translate.uses()
        
    setCurrent: (lang=null)=>
        if lang is null
            lang = @translate.uses()
        @current = lang unless lang is @current
        @translate.uses(@current)

angular.module('storiesServices').service "languagesService", LanguagesService