# minimalist service to handle the loading of supported languages stored 
# in locales/supported.json (generated by a grunt task here)
class LanguagesService
    @$inject: ['Restangular', '$translate', '$http']
    
    constructor: (Restangular, @translate, @http)->
        @list = Restangular.all('languages').getList()
        @current = @translate.uses()

        
    setCurrent: (lang=@translate.uses())=>
        @current = lang
        @translate.uses(@current)
        @updateDjangoLang(lang)

    updateDjangoLang: (lang)=>
        conf =
            method: 'POST'
            url: '/i18n/setlang/'
            data:
                language: lang

        @http(conf)

angular.module('storiesServices').service "languagesService", LanguagesService